version: '2.1'

networks:
  monitor-net:
    driver: bridge
services:
  poifier-client:
    container_name: poifier-client
    image: grassets/poifier-client
    networks:
       - monitor-net
    restart: unless-stopped
    tty: true
    command:
      - '/usr/bin/env'
      - 'python3'
      - '/opt/poifier/poifier-client.py'
      - '--poifier-token=<POIFIER_TOKEN>'
      - '--poifier-server=POIFIER_SERVER'
      - '--ethereum-endpoint=<ETHEREUM_ENDPOINT>'
      - '--mainnet-subgraph-endpoint=<MAINNET_GRAPH_SUBGRAPH>'
      - '--graph-node-status-endpoint=<GRAPH_NODE_ENDPOINT>'
